# -*- coding: utf-8 -*-
"""Generate sw.js with a VERSION derived from the hash of every shipped file.

Any content change produces a different sw.js, which is the only thing that makes a
browser install a new worker — so updates can never be forgotten.

Strategy:
  text  (html/css/js/json/webmanifest) -> network-first with a short timeout, cache fallback
  media (jpg/png)                      -> cache-first (big, and a changed file changes VERSION)
"""
import hashlib, json, pathlib

ROOT = pathlib.Path(__file__).parent.parent

FILES = ["index.html", "app.css", "app.js", "manifest.webmanifest",
         "data/days.json", "data/bible.json", "data/art.json",
         "data/people.json", "data/bg.json",
         "assets/icon-180.png", "assets/icon-192.png", "assets/icon-512.png"]
FILES += [f"assets/art/day{n:02d}.jpg" for n in range(1, 36)]
FILES += sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / "assets" / "bg").glob("*.jpg"))

missing = [f for f in FILES if not (ROOT / f).exists()]
if missing:
    raise SystemExit(f"missing files, refusing to build sw.js: {missing}")

h = hashlib.sha256()
for f in FILES:
    h.update(f.encode())
    h.update((ROOT / f).read_bytes())
VERSION = "devo-" + h.hexdigest()[:10]

ASSETS = ["./"] + FILES

TPL = """/* Offline shell — GENERATED by scripts/build_sw.py. Do not hand-edit.
   VERSION is a hash of every shipped file, so any content change ships a new worker. */
const VERSION = '__VERSION__';
const ASSETS = __ASSETS__;
const TEXT = /(?:\\.(?:html|css|js|json|webmanifest)|\\/)$/;
const NET_TIMEOUT = 3000;

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    for (const u of ASSETS) {
      try {
        const res = await fetch(u, {cache: 'reload'});
        if (res.ok) await cache.put(u, res);
      } catch (err) { /* keep going; a missing file must not break install */ }
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

function timeout(ms) {
  return new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), ms));
}

async function networkFirst(req) {
  try {
    const res = await Promise.race([fetch(req, {cache: 'no-cache'}), timeout(NET_TIMEOUT)]);
    if (res && res.ok) {
      const cache = await caches.open(VERSION);
      cache.put(req, res.clone()).catch(() => {});
      return res;
    }
    throw new Error('bad response');
  } catch (err) {
    const hit = await caches.match(req, {ignoreSearch: true});
    if (hit) return hit;
    if (req.mode === 'navigate') {
      const shell = await caches.match('index.html') || await caches.match('./');
      if (shell) return shell;
    }
    throw err;
  }
}

async function cacheFirst(req) {
  const hit = await caches.match(req, {ignoreSearch: true});
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) {
    const cache = await caches.open(VERSION);
    cache.put(req, res.clone()).catch(() => {});
  }
  return res;
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  const isText = req.mode === 'navigate' || TEXT.test(url.pathname);
  e.respondWith(isText ? networkFirst(req) : cacheFirst(req));
});
"""

out = (TPL.replace("__VERSION__", VERSION)
          .replace("__ASSETS__", json.dumps(ASSETS, indent=2)))
(ROOT / "sw.js").write_text(out)

total = sum((ROOT / f).stat().st_size for f in FILES)
print(f"sw.js -> VERSION {VERSION}")
print(f"{len(ASSETS)} precache entries, {total/1048576:.2f} MB of shipped files")
